In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/611noorsaeed/Heart-Disease-Prediction-System-Python-machine-learning/refs/heads/main/datasets_4123_6408_framingham.csv')
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   
4238     1   40        3.0              0         0.0     0.0   
4239     0   39        3.0              1        30.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   
4238                0             1         0    185.0  141.0   98.0  25.60   
4239                0             0         0    196.0  133.0   86.0  20.91   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  
4238       67.0     72.0           0  
4239       85.0     80.0           0  

[4240 rows x 16 columns]

In [4]:
df.shape

(4240, 16)

In [5]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [6]:
df.drop('education',axis=1,inplace=True)

In [7]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4240 non-null   int64  
 1   age              4240 non-null   int64  
 2   currentSmoker    4240 non-null   int64  
 3   cigsPerDay       4211 non-null   float64
 4   BPMeds           4187 non-null   float64
 5   prevalentStroke  4240 non-null   int64  
 6   prevalentHyp     4240 non-null   int64  
 7   diabetes         4240 non-null   int64  
 8   totChol          4190 non-null   float64
 9   sysBP            4240 non-null   float64
 10  diaBP            4240 non-null   float64
 11  BMI              4221 non-null   float64
 12  heartRate        4239 non-null   float64
 13  glucose          3852 non-null   float64
 14  TenYearCHD       4240 non-null   int64  
dtypes: float64(8), int64(7)
memory usage: 497.0 KB


In [8]:
!pip install scikit-learn

In [9]:
from sklearn.compose import ColumnTransformer

In [11]:
from sklearn.impute import SimpleImputer

In [13]:
simple=SimpleImputer(strategy='mean')

In [14]:
columns=['cigsPerDay','BPMeds','totChol','BMI','heartRate','glucose']

In [16]:
df[columns]=simple.fit_transform(df[columns])

In [17]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [19]:
df['TenYearCHD'].value_counts()

TenYearCHD
0    3596
1     644
Name: count, dtype: int64

In [20]:
from imblearn.over_sampling import SMOTE

In [23]:
x=df.drop('TenYearCHD',axis=1)
y=df['TenYearCHD']

In [24]:
smote=SMOTE()
x_resampled,y_resampled=smote.fit_resample(x,y)

In [25]:
x_resampled

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0        1   39              0         0.0     0.0                0   
1        0   46              0         0.0     0.0                0   
2        1   48              1        20.0     0.0                0   
3        0   61              1        30.0     0.0                0   
4        0   46              1        23.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
7187     0   62              1        20.0     0.0                0   
7188     1   45              1        20.0     0.0                0   
7189     0   52              0         0.0     0.0                0   
7190     1   48              1        20.0     0.0                0   
7191     0   56              0         0.0     0.0                0   

      prevalentHyp  diabetes     totChol       sysBP       diaBP        BMI  \
0                0         0  195.000000  106.000000   70.000000  26.970000   
1                0         0  250.000000  121.000000   81.000000  28.730000   
2                0         0  245.000000  127.500000   80.000000  25.340000   
3                1         0  225.000000  150.000000   95.000000  28.580000   
4                0         0  285.000000  130.000000   84.000000  23.100000   
...            ...       ...         ...         ...         ...        ...   
7187             1         0  228.428231  140.974810   81.773290  25.963431   
7188             0         0  266.871335  119.457112   79.564332  24.526702   
7189             1         0  240.000000  174.727456  103.045491  29.325966   
7190             1         0  268.831068  163.566214  101.036505  26.913235   
7191             0         0  219.729480  121.458959   73.481503  25.576139   

      heartRate     glucose  
0     80.000000   77.000000  
1     95.000000   76.000000  
2     75.000000   70.000000  
3     65.000000  103.000000  
4     85.000000   85.000000  
...         ...         ...  
7187  82.201520   81.251900  
7188  78.828447   86.650109  
7189  81.454912   74.090982  
7190  92.264854   80.132427  
7191  71.270520   93.090173  

[7192 rows x 14 columns]

In [28]:
y_resampled

0       0
1       0
2       0
3       1
4       0
       ..
7187    1
7188    1
7189    1
7190    1
7191    1
Name: TenYearCHD, Length: 7192, dtype: int64

# Train Test Split

In [33]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)

In [37]:
x_train

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
6256     1   40              1   22.652796     0.0                0   
4668     0   39              1   10.788180     0.0                0   
940      0   53              0    0.000000     0.0                0   
1511     0   38              0    0.000000     0.0                0   
6034     0   51              0    0.120960     0.0                0   
...    ...  ...            ...         ...     ...              ...   
3772     1   39              1   10.000000     0.0                0   
5191     0   53              1    6.678935     0.0                0   
5226     1   58              0    0.000000     0.0                0   
5390     0   37              1   20.000000     0.0                0   
860      0   35              0    0.000000     0.0                0   

      prevalentHyp  diabetes     totChol       sysBP       diaBP        BMI  \
6256             0         0  250.040745  111.020373   69.673168  23.231188   
4668             0         0  161.545502  101.348588   65.484833  21.345340   
940              1         0  284.000000  167.500000  102.500000  31.500000   
1511             0         0  255.000000  125.000000   85.000000  23.050000   
6034             1         0  267.927424  205.911296  115.951616  26.299519   
...            ...       ...         ...         ...         ...        ...   
3772             0         0  215.000000  102.000000   64.500000  24.500000   
5191             0         0  274.518402  131.870399   89.321065  27.409060   
5226             0         0  208.975367  133.385220   83.897537  26.048829   
5390             0         0  301.927840  118.956382   88.565428  30.938798   
860              0         0  248.000000  107.000000   73.000000  20.640000   

      heartRate    glucose  
6256  87.550932  60.101864  
4668  71.606172  71.969665  
940   88.000000  87.000000  
1511  72.000000  73.000000  
6034  97.814528  69.943552  
...         ...        ...  
3772  68.000000  62.000000  
5191  67.061864  76.321065  
5226  59.024633  77.307390  
5390  72.115779  80.313001  
860   90.000000  80.000000  

[5753 rows x 14 columns]

In [38]:
y_train

6256    1
4668    1
940     0
1511    0
6034    1
       ..
3772    0
5191    1
5226    1
5390    1
860     0
Name: TenYearCHD, Length: 5753, dtype: int64

In [39]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [42]:
x_train_scaled

array([[ 1.27269918, -1.37168786,  1.09123071, ..., -0.7249082 ,
         0.97169313, -0.82934094],
       [-0.78573163, -1.49354271,  1.09123071, ..., -1.20590953,
        -0.39465771, -0.41590932],
       [-0.78573163,  0.21242522, -0.9163965 , ...,  1.38412194,
         1.01017502,  0.1076936 ],
       ...,
       [ 1.27269918,  0.82169949, -0.9163965 , ..., -0.00624516,
        -1.4728047 , -0.22996215],
       [-0.78573163, -1.73725242,  1.09123071, ...,  1.24098276,
        -0.35098806, -0.12525746],
       [-0.78573163, -1.98096212, -0.9163965 , ..., -1.38581241,
         1.18156058, -0.13616128]])

In [43]:
from sklearn.ensemble import RandomForestClassifier

# Final Model

In [62]:
rf_classifier=RandomForestClassifier()

In [63]:
rf_classifier.fit(x_train_scaled,y_train)
y_pred=rf.predict(x_test_scaled)

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [64]:
print('accuracy_score :',accuracy_score(y_test,y_pred))
print('classification_report :',classification_report(y_test,y_pred))
print('confusion_matrix :',confusion_matrix(y_test,y_pred))

accuracy_score : 0.8943710910354413
classification_report :               precision    recall  f1-score   support

           0       0.91      0.89      0.90       745
           1       0.88      0.90      0.89       694

    accuracy                           0.89      1439
   macro avg       0.89      0.89      0.89      1439
weighted avg       0.89      0.89      0.89      1439

confusion_matrix : [[662  83]
 [ 69 625]]


# Show each model Results

In [58]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix


# Define a list of classifiers
classifiers = [
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    GaussianNB(),
    XGBClassifier()
]

# Create a dictionary to store the results
results = {}


# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(x_train_scaled, y_train)
    y_pred = clf.predict(x_test_scaled)

# Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")
    
    # Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(y_test, y_pred))
    
    # Confusion matrix
    print(f"Confusion Matrix for {clf_name}:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

RandomForestClassifier Accuracy: 0.886726893676164
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       745
           1       0.88      0.88      0.88       694

    accuracy                           0.89      1439
   macro avg       0.89      0.89      0.89      1439
weighted avg       0.89      0.89      0.89      1439

Confusion Matrix for RandomForestClassifier:
[[663  82]
 [ 81 613]]


C:\Users\anish\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier Accuracy: 0.7282835302293259
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.73      0.75      0.74       745
           1       0.72      0.70      0.71       694

    accuracy                           0.73      1439
   macro avg       0.73      0.73      0.73      1439
weighted avg       0.73      0.73      0.73      1439

Confusion Matrix for AdaBoostClassifier:
[[559 186]
 [205 489]]
GradientBoostingClassifier Accuracy: 0.8047255038220987
Classification Report for GradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       745
           1       0.80      0.79      0.80       694

    accuracy                           0.80      1439
   macro avg       0.80      0.80      0.80      1439
weighted avg       0.80      0.80      0.80      1439

Confusion Matrix for GradientBoostingClassifier:
[[607 138]
 [143 551]]
Logist

In [73]:
import pickle
pickle.dump(rf_classifier,open('rf_classifier.pkl','wb'))
pickle.dump(scaler,open('scaler.pkl','wb'))

In [74]:
import pickle

# Load the RandomForestClassifier model
with open("rf_classifier.pkl", "rb") as file:
    rf_classifier = pickle.load(file)

# Load the scaler
with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [68]:
!pip install numpy

# predictive system

In [69]:
import numpy as np

def predict(model, scaler, male, age, currentSmoker, cigsPerDay, BPMeds, prevalentStroke, prevalentHyp, diabetes, totChol, sysBP, diaBP, BMI, heartRate, glucose):
    # Encode categorical variables
    male_encoded = 1 if male.lower() == "male" else 0
    currentSmoker_encoded = 1 if currentSmoker.lower() == "yes" else 0
    BPMeds_encoded = 1 if BPMeds.lower() == "yes" else 0
    prevalentStroke_encoded = 1 if prevalentStroke.lower() == "yes" else 0
    prevalentHyp_encoded = 1 if prevalentHyp.lower() == "yes" else 0
    diabetes_encoded = 1 if diabetes.lower() == "yes" else 0
    
    # Prepare features array
    features = np.array([[male_encoded, age, currentSmoker_encoded, cigsPerDay, BPMeds_encoded, prevalentStroke_encoded, prevalentHyp_encoded, diabetes_encoded, totChol, sysBP, diaBP, BMI, heartRate, glucose]])
    
    # scalling
    scaled_features = scaler.transform(features)
    
    # predict by model
    result = model.predict(scaled_features)
    
    return result[0]

In [70]:
# test 1:
male = "female"
age = 56.00
currentSmoker = "yes"
cigsPerDay = 3.00
BPMeds = "no"
prevalentStroke = "no"
prevalentHyp = "yes"
diabetes = 'no'
totChol = 285.00
sysBP = 145.00
diaBP = 100.00
BMI = 30.14
heartRate = 80.00
glucose = 86.00


result = predict(rf_classifier, scaler, male, age, currentSmoker, cigsPerDay, BPMeds, prevalentStroke, prevalentHyp, diabetes, totChol, sysBP, diaBP, BMI, heartRate, glucose)


if result == 1:
    print("The Patient has Heart Diseas")
else: 
    print("The Patiennt has No Heart Deseas")

The Patiennt has No Heart Deseas


C:\Users\anish\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [72]:
male = 'female'
age = 63.0
currentSmoker = 'yes'
cigsPerDay = 3.0
BPMeds = 'no'
prevalentStroke = 'no'
prevalentHyp = 'yes'
diabetes = 'no'
totChol = 267.0
sysBP = 156.5
diaBP = 92.5
BMI = 27.1
heartRate = 60.0
glucose = 79.0
result = 1.0



result = predict(rf_classifier, scaler, male, age, currentSmoker, cigsPerDay, BPMeds, prevalentStroke, prevalentHyp, diabetes, totChol, sysBP, diaBP, BMI, heartRate, glucose)


if result == 1:
    print("The Patient has Heart Diseas")
else: 
    print("The Patiennt has No Heart Deseas")

The Patiennt has No Heart Deseas


C:\Users\anish\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
